## Exercicio 1

In [1]:
import numpy as np

def transformation(y1, y2):
    res = []

    for i in range(len(y1)):
        res.append([1, y1[i] * y2[i]])

    return np.array(res)

y1 = np.array([1, 1, 3, 3, 2])
y2 = np.array([1, 3, 2, 3, 4])

X = transformation(y1, y2)
Z = np.array([[1.25], [7.0], [2.7], [3.2], [5.5]])

XT = X.T
X_mul_XT = np.dot(XT, X)
X_mul_XT_inv = np.linalg.pinv(X_mul_XT)

W = np.dot(np.dot(X_mul_XT_inv, XT), Z)
print(W)


[[3.3159292 ]
 [0.11371681]]


## Exercicio 2

In [26]:
import numpy as np

def transformation(y1, y2):
    res = []

    for i in range(len(y1)):
        res.append([1, y1[i] * y2[i]])

    return np.array(res)

y1 = np.array([1, 1, 3, 3, 2])
y2 = np.array([1, 3, 2, 3, 4])

X = transformation(y1, y2)
Z = np.array([[1.25], [7.0], [2.7], [3.2], [5.5]])

XT = X.T
I = np.eye(2)
X_mul_XT = np.dot(XT, X)
X_mul_XT_inv = np.linalg.pinv(X_mul_XT+ I)
print(X_mul_XT_inv)

W = np.dot(np.dot(X_mul_XT_inv, XT), Z)
print(W)

[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]
[[1.81808511]
 [0.32375887]]


Com a introdução da regularização (Ridge Regression), como era esperado, observamos que os coeficientes foram reduzidos, aproximando-se de zero. Esse ajuste contribui para reduzir a complexidade do modelo e, consequentemente, ajuda a prevenir o overfitting, melhorando a capacidade de generalização.

## Exercicio 3

#### RMSE - Regressão Linear

In [2]:
print("Para a regressão linear utilizando a forma fechada OLS")
import numpy as np

def transformation(y1, y2):
    res = []

    for i in range(len(y1)):
        res.append([1, y1[i] * y2[i]])

    return np.array(res)

def calculateRMSE(expected_values, real_values):
    res = 0
    for i in range(len(expected_values)):
        res += ((real_values[i][0] - expected_values[i][0])**2) / len(expected_values)
    
    return np.sqrt(res)

y1_train = np.array([1, 1, 3, 3, 2])
y2_train = np.array([1, 3, 2, 3, 4])

X = transformation(y1, y2)
Z = np.array([[1.25], [7.0], [2.7], [3.2], [5.5]]) # Valores reais das observações do DataSet

y1_new = np.array([2, 1, 5])
y2_new = np.array([2, 2, 1])

new_X = transformation(y1_new, y2_new)
new_Z = np.array([[0.7], [1.1], [2.2]]) # Valores reais das novas observações

# Cálculo apenas com X e Z pois utilizámos apenas as observações do DataSet
# para fazer a regressão linear
XT = X.T
X_mul_XT = np.dot(XT, X)
X_mul_XT_inv = np.linalg.pinv(X_mul_XT)
W = np.dot(np.dot(X_mul_XT_inv, XT), Z)

# Valores esperados para todas as observações
Z_esperado_train = np.dot(X, W)
print(f"Valores Esperados para as observações de treino: \n{Z_esperado_train}")

Z_esperado_new = np.dot(new_X, W)
print(f"Valores Esperados para as observações novas: \n{Z_esperado_new}")

print()

print(f"RMSE de treino = {calculateRMSE(Z_esperado_train, Z)}")
print(f"RMSE com observações novas = {calculateRMSE(Z_esperado_new, new_Z)}")

Para a regressão linear utilizando a forma fechada OLS
Valores Esperados para as observações de treino: 
[[3.42964602]
 [3.65707965]
 [3.99823009]
 [4.33938053]
 [4.22566372]]
Valores Esperados para as observações novas: 
[[3.77079646]
 [3.54336283]
 [3.88451327]]

RMSE de treino = 2.0264992265096593
RMSE com observações novas = 2.465589706294614


#### RMSE - Ridge Regression

In [31]:
print("Para a Ridge Regression com fator de penalidade lambda = 1")
import numpy as np

def transformation(y1, y2):
    res = []

    for i in range(len(y1)):
        res.append([1, y1[i] * y2[i]])

    return np.array(res)

def calculateRMSE(expected_values, real_values):
    res = 0
    for i in range(len(expected_values)):
        res += ((real_values[i][0] - expected_values[i][0])**2) / len(expected_values)
    
    return np.sqrt(res)

y1_train = np.array([1, 1, 3, 3, 2])
y2_train = np.array([1, 3, 2, 3, 4])

X = transformation(y1, y2)
Z = np.array([[1.25], [7.0], [2.7], [3.2], [5.5]]) # Valores reais das observações do DataSet

y1_new = np.array([2, 1, 5])
y2_new = np.array([2, 2, 1])

new_X = transformation(y1_new, y2_new)
new_Z = np.array([[0.7], [1.1], [2.2]]) # Valores reais das novas observações


# Cálculo apenas com X e Z pois utilizámos apenas as observações do DataSet
# para fazer a regressão linear
XT = X.T
I = np.eye(2) # Matriz identidade, como lamda = 1, é apenas a identidade que precisamos de somar
X_mul_XT = np.dot(XT, X)
X_mul_XT_inv = np.linalg.pinv(X_mul_XT+ I)
W = np.dot(np.dot(X_mul_XT_inv, XT), Z)

# Valores esperados para todas as observações
Z_esperado_train = np.dot(X, W)
print(f"Valores Esperados para as observações de treino: \n{Z_esperado_train}")

Z_esperado_new = np.dot(new_X, W)
print(f"Valores Esperados para as observações novas: \n{Z_esperado_new}")

print()

print(f"RMSE de treino = {calculateRMSE(Z_esperado_train, Z)}")
print(f"RMSE com observações novas = {calculateRMSE(Z_esperado_new, new_Z)}")

Para a Ridge Regression com fator de penalidade lambda = 1
[[1.81808511]
 [0.32375887]]

Valores Esperados para as observações de treino: 
[[2.14184397]
 [2.7893617 ]
 [3.7606383 ]
 [4.73191489]
 [4.40815603]]
Valores Esperados para as observações novas: 
[[3.11312057]
 [2.46560284]
 [3.43687943]]

RMSE de treino = 2.1535412995264682
RMSE com observações novas = 1.75289215409223


Como o RMSE nos dados de teste para o modelo regularizado (Ridge) é menor do que o RMSE do modelo não regularizado, podemos concluir que a regularização melhorou a capacidade de generalização do modelo, reduzindo o erro e tornando as previsões mais precisas, o que era esperado devido à penalização de coeficientes excessivamente altos.

Por outro lado, o RMSE nos dados de treino é maior no modelo regularizado do que no modelo não regularizado. Isto ocorre porque a regularização impõe restrições nos coeficientes, evitando que o modelo se ajuste demasiado aos dados de treino (overfitting), o que leva a um maior erro nesse conjunto.

No entanto, esta ligeira perda de desempenho para os dados de treino é compensada por uma melhor performance nos dados de teste, indicando que o modelo regularizado está menos suscetível a overfitting e, portanto, tem maior capacidade de generalização.

## Exercicio 4

In [1]:
import numpy as np

def transformation(y1, y2):
    res = []

    for i in range(len(y1)):
        res.append([1, y1[i] * y2[i]])

    return np.array(res)

def softmax(Z_out):
    exp_z = np.exp(Z_out)
    return exp_z / np.sum(exp_z)

# Fórmula geral do update
def update(to_update, learning_rate, grad_loss):
    return to_update - learning_rate * grad_loss

# Cálculo do gradiante_out quando softmax + cross entropy loss
def calculate_out_gradiant(X_out, t):
    return X_out - t

# Cálculo dos gradientes intermédios (não há função de ativação)
def calculate_intermedian_gradiant(W_i_plus_1, grad_loss_i_plus_1):
    return np.dot(W_i_plus_1, grad_loss_i_plus_1)
# Forward Propagation cálculo
y1 = [1]
y2 = [1]

X_0 = transformation(y1, y2).T
W_1 = np.array([[0.1 , 0.1], [0.1, 0.2], [0.2, 0.1]])
b_1 = np.array([[0.1], [0], [0.1]])

Z_1 = np.dot(W_1, X_0) + b_1 # Hidden layers não têm função de ativação

W_2 = np.array([[1, 2, 2], [1, 2, 1], [1, 1, 1]])
X_1 = Z_1
b_2 = np.array([[1], [1], [1]])

Z_2 = np.dot(W_2, X_1) + b_2
X_2 = softmax(Z_2) # Output Layer
print(f" X_2:\n{X_2}\n")

# Back Propagation cálculo
X_out = X_2
t = np.array([[0], [1], [0]]) # Valor real é o B, daí ter o segundo bit a 1

G_2 = calculate_out_gradiant(X_out, t)
W_2_new = update(W_2, 0.1, np.dot(G_2, X_1.T))
b_2_new = update(b_2, 0.1, G_2)
print(f"New W_2 Weights:\n{W_2_new}\n")
print(f"New b_2 bias:\n{b_2_new}\n")

G_1 = calculate_intermedian_gradiant(W_2.T, G_2)
W_1_new = update(W_1, 0.1, np.dot(G_1, X_0.T))
b_1_new = update(b_1, 0.1, G_1)
print(f"New W_1 Weights:\n{W_1_new}\n")
print(f"New b_1 bias:\n{b_1_new}\n")


 X_2:
[[0.46148762]
 [0.3093444 ]
 [0.22916797]]

New W_2 Weights:
[[0.98615537 1.98615537 1.9815405 ]
 [1.02071967 2.02071967 1.02762622]
 [0.99312496 0.99312496 0.99083328]]

New b_2 bias:
[[0.95385124]
 [1.06906556]
 [0.9770832 ]]

New W_1 Weights:
[[0.1        0.1       ]
 [0.1229168  0.2229168 ]
 [0.15385124 0.05385124]]

New b_1 bias:
[[0.1       ]
 [0.0229168 ]
 [0.05385124]]

